replicaCount: 1
image:
  repository: maksalena/server_app
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: "0.5"
    memory: "512Mi"
  requests:
    cpu: "0.25"
    memory: "256Mi"

probes:
  liveness:
    path: /
    port: http
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /
    port: http
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 3
